import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Objects;

/**
 * This class is for creating customer objects with functionalities
 */
public class Customer implements Serializable {
    private static int idRep;
    private int id;
    private String name;
    private String mail;
    private String phone;
    private String licenseNumber;
    private final ArrayList<Renting> vehicleRentingDates;


    public Customer(String name, String mail, String phone, String licenseNumber) {
        vehicleRentingDates = new ArrayList<>();
        this.name = name;
        this.mail = mail;
        this.phone = phone;
        id = ++idRep;
        this.licenseNumber = licenseNumber;
    }

    /**
     * every customer should have an ID in this system which should be generated by this method
     * @param idRep static id fild which keep the count of customers
     */
    public static void setIdRep(int idRep) {
        Customer.idRep = idRep;
    }

    public String getLicenseNumber() {
        return licenseNumber;
    }

    public String getName() {
        return name;
    }
    public int getID() {
        return id;
    }

    /**
     * keeps the renting details of vehicles
     * @param info renting information
     */
    public void addVehicleRentingDate(Renting info){
        vehicleRentingDates.add(info);
    }

    public ArrayList<Renting> getVehicleRentingDates() {
        return vehicleRentingDates;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Customer customer = (Customer) o;
        return getID() == customer.getID();
    }

    @Override
    public String toString() {
        if(phone != null && mail != null)
            return "ID: "+ id+
                    ", name: " + name +
                    ", mail: " + mail +
                    ", phone: " + phone+
                    ", license number:  "+ licenseNumber;
        else if(phone != null)
            return "ID: "+ id+", name: " + name +
                    ", phone: " + phone+", license number:  "+ licenseNumber;
        else
            return "ID: "+ id+", name: " + name+
                    ", mail: " + mail+", license number:  "+ licenseNumber;
    }
}

